GET http://localhost:7007/api/auth/demo
###
POST http://localhost:7007/api/auth/register

{
    "username": "admin",
    "password": "test123"
}
###
POST http://localhost:7007/api/auth/login

{
    "username": "admin",
    "password": "test123"
}
###
GET http://localhost:7007/api/protected/user_demo
Authorization: Bearer eyJhGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTgwMjcxNCwicm9sZXMiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbiJ9.Ugxj9rrveLHqnEeeRiGYH1zjOxJhd5-PLJe5Rma4LMY
###
GET http://localhost:7007/api/protected/admin_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjk3MDQxNjQ4LCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InRlc3QifQ.8b7o0ADrpO11iBfIkyb9RHvgZBD6MXf8xoy9DIG_j6o
###
